### ISSUE TITLE
Start error problem

### ISSUE THREAD

**Issue by 1769948908** [RMASBench/RMASBench#1]
12:44:40.949 [Thread-74] INFO  RSLBench.PlatoonFireAgent - Sample fire brigade connected: max extinguish distance = 50000, max power = 500, max tank = 7500000
12:44:41.050 [main] INFO  RSLBench.Launcher - Connecting fire brigade 19...
12:44:41.057 [main] INFO  RSLBench.Launcher - failed: No more agents
12:44:41.057 [main] INFO  RSLBench.Launcher - Connecting police force 20...
12:44:41.060 [main] INFO  RSLBench.Launcher - failed: No more agents
12:44:41.060 [main] INFO  RSLBench.Launcher - Connecting center 21...
12:44:41.062 [main] INFO  RSLBench.CenterAgent - Center Agent CREATED
12:44:41.119 [Thread-84] INFO  RSLBench.CenterAgent - Center Agent connected
Exception in thread "Thread-84" rescuecore2.config.NoSuchConfigOptionException: util.class
    at rescuecore2.config.Config.getValue(Config.java:287)
    at RSLBench.CenterAgent.initializeParameters(CenterAgent.java:143)
    at RSLBench.CenterAgent.postConnect(CenterAgent.java:121)
    at rescuecore2.components.AbstractComponent.postConnect(AbstractComponent.java:76)
    at rescuecore2.components.AbstractAgent.postConnect(AbstractAgent.java:43)
    at rescuecore2.components.AbstractAgent$AgentConnectionListener.handleConnectOK(AbstractAgent.java:148)
    at rescuecore2.components.AbstractAgent$AgentConnectionListener.messageReceived(AbstractAgent.java:138)
    at rescuecore2.connection.AbstractConnection$MessageBroadcastThread.work(AbstractConnection.java:283)
    at rescuecore2.misc.WorkerThread.run(WorkerThread.java:48)

**Comment by kilburn** [comment]
During the last merge from development the `RSLB2/boot/config/.example.cfg.dist` file lost the utility configuration settings (see https://github.com/RMASBench/RSLB2/commit/27835849c4bc656d429885b816a3d2ac9a6fe920#diff-e0d85fc4ab0cfa08ae01e939aaf74295).

You can either copy the utility settings from that link into your `example.cfg` file or wait a bit untill I commit a fix for it.

Sorry for the inconvenience.

**Comment by 1769948908** [comment]
Hi,
     Thank you very much!  
      I was doing RoboCup rescue Agent competition,I was a member of the Apollo Rescue of Nanjing University of Posts and Telecommunications .  I come from China.How to use this platform in the RoboCup 2015 ?How can we use this platform?what needs to be done? write code based your code or others?
Can you give me some help?

Thanks!
Apollo Rescue,
Liu.Huifei
